export const CartActionTypes = {
  ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
  DECREASE_QUANTITY: 'DECREASE_QUANTITY',
  INCREASE_QUANTITY: 'INCREASE_QUANTITY',
  REMOVE_ITEM_ORDER_FROM_CART: 'REMOVE_ITEM_ORDER_FROM_CART',
  CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
  CLEAR_LIST: 'CLEAR_LIST',
};
