export const FavouriteActionTypes = {
  TOOGLE_FAVOURITE_HIDDEN: 'TOOGLE_FAVOURITE_HIDDEN',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  CLEAR_ITEM_FROM_LIST: 'CLEAR_ITEM_FROM_LIST',
  CLEAR_LIST: 'CLEAR_LIST',
};
