export const FavouriteActionTypes = {
  // TOOGLE_FAVOURITE: 'TOOGLE_FAVOURITE',
  ADD_ITEM_TO_FAVOURITE: 'ADD_ITEM_TO_FAVOURITE',
  REMOVE_ITEM_FROM_FAVOURITE: 'REMOVE_ITEM_FROM_FAVOURITE',
  CLEAR_ITEM_FROM_LIST: 'CLEAR_ITEM_FROM_LIST',
  CLEAR_LIST: 'CLEAR_LIST',
};
